"""Code completed by Raphael Reme"""

import sys
sys.path.insert(0, './utils')
import numpy as np
import matplotlib.pyplot as plt
import math
from cliffwalk import CliffWalk
import time
import sys


def time_consumption(func):
    """Decorator that will print the time duration of any function."""
    def wrapper(*args, **kwargs):
        t = time.time()
        res = func(*args, **kwargs)
        print(f"Computationnal time of {func.__name__}:", time.time() - t)
        return res
    return wrapper


def policy_evaluation(P, R, policy, gamma=0.9, tol=1e-2):
    """
    Args:
        P: np.array
            transition matrix (NsxNaxNs)
        R: np.array
            reward matrix (NsxNa)
        policy: np.array
            matrix mapping states to action (Ns)
        gamma: float
            discount factor
        tol: float
            precision of the solution
    Return:
        value_function: np.array
            The value function of the given policy
    """
    Ns, _ = R.shape
    R_pi = np.zeros(Ns)  # R_pi[s] = R[s, pi(s)]
    P_pi = np.zeros((Ns, Ns))  # P_pi[s,s'] = p(s'|s, pi(s))
    for s in range(Ns):
        a = policy[s]
        R_pi[s] = R[s, a]
        for s_prime in range(Ns):
            P_pi[s, s_prime] = P[s, a, s_prime]

    # V = R_pi + gamma * P_pi.V
    # (Id - gamma * P_pi).V = R_pi
    # use a linear system to find V. Could have used the fact that he is a fixed point of the bellman equation to.
    return np.linalg.solve(np.identity(Ns) - gamma * P_pi, R_pi)


@time_consumption
def policy_iteration(P, R, gamma=0.9, tol=1e-3):
    """
    Args:
        P: np.array
            transition matrix (NsxNaxNs)
        R: np.array
            reward matrix (NsxNa)
        gamma: float
            discount factor
        tol: float
            precision of the solution
    Return:
        policy: np.array
            the final policy
        V: np.array
            the value function associated to the final policy
    """
    Ns, Na = R.shape
    V = np.zeros(Ns)
    policy = np.zeros(Ns, dtype=np.int)
    # policy = np.random.randint(0, Na, Ns, dtype=int)  # Can test with a random policy initialization

    next_V = policy_evaluation(P, R, policy, gamma, tol)
    i = 0
    while not (next_V == V).all():
        V = next_V
        i+=1
        for s in range(Ns):
            policy[s] = np.argmax(R[s] + gamma * P[s] @ next_V)
        next_V = policy_evaluation(P, R, policy, gamma, tol)
    print("Iterations:", i)

    return policy, V


@time_consumption
def value_iteration(P, R, gamma=0.9, tol=1e-3):
    """
    Args:
        P: np.array
            transition matrix (NsxNaxNs)
        R: np.array
            reward matrix (NsxNa)
        gamma: float
            discount factor
        tol: float
            precision of the solution
    Return:
        Q: final Q-function (at iteration n)
        greedy_policy: greedy policy wrt Qn
        Qfs: all Q-functions generated by the algorithm (for visualization)
    """
    Ns, Na = R.shape
    Q = np.zeros((Ns, Na))
    Qfs = [Q]
    i = 0

    while len(Qfs) <= 1 or (np.abs(Qfs[-1] - Qfs[-2]) > tol).any():
        i+=1
        Q = np.zeros((Ns, Na))
        for s in range(Ns):
            Q[s] = R[s] + gamma * P[s] @ np.max(Qfs[-1], axis=1)
        Qfs.append(Q)

    print("Iterations:", i)
    greedy_policy = np.argmax(Q, axis=1)
    return Q, greedy_policy, Qfs


# Edit below to run policy and value iteration on different environments and
# visualize the resulting policies in action!
# You may change the parameters in the functions below
if __name__ == "__main__":
    tol =1e-5
    env = CliffWalk(proba_succ=1)
    print(env.R.shape)
    print(env.P.shape)
    env.render()

    # run value iteration to obtain Q-values
    VI_Q, VI_greedypol, all_qfunctions = value_iteration(env.P, env.R, gamma=env.gamma, tol=tol)

    # render the policy
    print("[VI]Greedy policy: ")
    env.render_policy(VI_greedypol)

    # compute the value function of the greedy policy using matrix inversion
    greedy_V = policy_evaluation(env.P, env.R, VI_greedypol, env.gamma, tol)

    # show the error between the computed V-functions and the final V-function
    # (that should be the optimal one, if correctly implemented)
    # as a function of time
    norms = [ np.linalg.norm(q.max(axis=1) - greedy_V) for q in all_qfunctions]
    plt.plot(norms)
    plt.xlabel('Iteration')
    plt.ylabel('Error')
    plt.title("Value iteration: convergence")

    #### POLICY ITERATION ####
    PI_policy, PI_V = policy_iteration(env.P, env.R, gamma=env.gamma, tol=tol)
    print("\n[PI]final policy: ")
    env.render_policy(PI_policy)

    # control that everything is correct
    assert np.allclose(PI_policy, VI_greedypol),\
        "You should check the code, the greedy policy computed by VI is not equal to the solution of PI"
    assert np.allclose(PI_V, greedy_V),\
        "Since the policies are equal, even the value function should be"

    # for visualizing the execution of a policy, you can use the following code
    # state = env.reset()
    # env.render()
    # for i in range(15):
    #     action = VI_greedypol[state]
    #     state, reward, done, _ = env.step(action)
    #     env.render()

    plt.show()
